### ISSUE TITLE
add gmail

### ISSUE THREAD

**Issue by aofall** [LGA1150/Acrylated-imouto.host#2]
64.233.189.109 gmail-smtp-msa.l.google.com
64.233.189.27 gmail-smtp-in.l.google.com
64.233.189.14 gmr-smtp-in.l.google.com

**Comment by aofall** [comment]
gmr-smtp-in.l.google.com 、 gmail-smtp-in.l.google.com 开放25端口
没加密感觉意义不怎么大...........

**Comment by LGA1150** [comment]
Already exists.
